apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28 # new version - nginx:1.29.3
        ports:
        - containerPort: 80
-----------------------------------------------------------------------------------------------------------------------------------------------------------        
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        imagePullPolicy:  Always
        ports:
        - containerPort: 80
------------------------------------------------------------------------------------------------------------------------------------------------------------------
2ï¸âƒ£ ROLLING UPDATE (Reference)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 10    #A newly created Pod must stay in Ready state for at least 10 seconds before Kubernetes considers it Available.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28 # new version - nginx:1.29.3
        ports:
        - containerPort: 80

ðŸ”µ NodePort Service YAML
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007   # Optional (auto-assign if removed)

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1ï¸âƒ£ RECREATE Strategy

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28 # new version - nginx:1.29.3
        ports:
        - containerPort: 80

ðŸ”µ NodePort Service YAML
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80     # The Service will listen on port 80.  # Service is a virtual load balancer inside the cluster.
    targetPort: 80    # iptables (created by kube-proxy) forwards to: PodIP:targetPort
    nodePort: 30007   # You can change or remove this to auto-assign

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3ï¸âƒ£ BLUE-GREEN Deployment

 ðŸŸ¦ Blue (Current Version)
 apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        ports:
        - containerPort: 80

ðŸŸ© Green (New Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      version: green
  template:
    metadata:
      labels:
        app: nginx
        version: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.3  # nginxdemos/hello:0.4-plain-text
        ports:
        - containerPort: 80

ðŸ”„ Service Switch
Service initially points to blue:
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort   # Change to LoadBalancer if using cloud
  selector:
    app: nginx
    version: blue
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007

To switch to green:
selector:
  app: nginx
  version: green
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4ï¸âƒ£ CANARY Deployment

ðŸŸ¦ Stable Deployment (4 replicas)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      track: stable
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        ports:
        - containerPort: 80

ðŸŸ¨ Canary Deployment (1 replica)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      track: canary
  template:
    metadata:
      labels:
        app: nginx
        track: canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.3
        ports:
        - containerPort: 80

Both use same Service:
selector:
  app: nginx

-->Traffic split based on pod count:

4 stable
1 canary
~20% traffic to new version
It is simple round-robin / random distribution.












